### ISSUE TITLE
empty devTools window

### ISSUE THREAD

**Issue by theophane-girard** [CodeMooseUS/vscode-devtools#18] opened 2019-12-04 09:10 UTC
After selecting chrometab target, devtool window is empty :'(

![image](https://user-images.githubusercontent.com/11314829/70128782-cb8d9c80-167d-11ea-86c1-b26fa6e1fbf3.png)

vscode devtool show following message 

> [Embedded Page] Refused to load the script 'vscode-resource:/c%3A/Users/tgirard/.vscode/extensions/codemooseus.vscode-devtools-for-chrome-0.0.5/node_modules/chrome-devtools-frontend/front_end/Runtime.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://chrome-devtools-frontend.appspot.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
> 
> [Embedded Page] Refused to load the script 'vscode-resource:/c%3A/Users/tgirard/.vscode/extensions/codemooseus.vscode-devtools-for-chrome-0.0.5/node_modules/chrome-devtools-frontend/front_end/inspector.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://chrome-devtools-frontend.appspot.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
> 
> [Embedded Page] Uncaught SecurityError: Blocked a frame with origin "null" from accessing a frame with origin "null". Protocols, domains, and ports must match.

![image](https://user-images.githubusercontent.com/11314829/70128951-2cb57000-167e-11ea-8556-9b387b87427e.png)

**Comment by jm06487** [comment] 2019-12-31 07:22
I am having the same issue: 
[Embedded Page] Refused to load the script 'vscode-resource:/c%3A/Users/jaimemac/.vscode-insiders/extensions/codemooseus.vscode-devtools-for-chrome-0.0.5/node_modules/chrome-devtools-frontend/front_end/Runtime.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://chrome-devtools-frontend.appspot.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
webviewElement.ts:241 [Embedded Page] Refused to load the script 'vscode-resource:/c%3A/Users/jaimemac/.vscode-insiders/extensions/codemooseus.vscode-devtools-for-chrome-0.0.5/node_modules/chrome-devtools-frontend/front_end/inspector.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://chrome-devtools-frontend.appspot.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
webviewElement.ts:241 [Embedded Page] Uncaught SecurityError: Blocked a frame with origin "null" from accessing a frame with origin "null". Protocols, domains, and ports must match.

**Comment by BlankSourceCode** [comment] 2020-01-26 01:17
Yes, this was caused by a change in VS Code that updated to a new version of Electron (which contained a chromium version with newer security checks).

I haven't had much time to devote to this project, but it should be fixed in version 0.0.6 of the extension.

**Closed as completed by BlankSourceCode** 2020-01-26 01:17 UTC
